# Generated by Django 4.2.30 on 2026-07-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='variante_info',
            field=models.CharField(blank=True, help_text='Ej: Tamanho M / Cor Azul', max_length=100),
        ),
    ]
