# Generated by Django 4.2.30 on 2026-07-20 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_itempedido_variante_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor número = primero)')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_adicionales', to='tienda.producto')),
            ],
            options={
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['orden'],
            },
        ),
    ]
