# Generated by Django 4.2.30 on 2026-07-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_imagenproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_mantenimiento', models.BooleanField(default=False, help_text='Si está activo, los visitantes verán una página de mantenimiento')),
                ('mensaje_mantenimiento', models.TextField(default='Estamos realizando mejoras. Voltamos em breve!', help_text='Mensaje que verán los visitantes durante el mantenimiento')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
    ]
