# Generated by Django 4.2.30 on 2026-07-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_configuracionsitio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('clasificacion', models.CharField(choices=[('lead', 'Lead (Potencial)'), ('activo', 'Cliente Ativo'), ('inactivo', 'Cliente Inativo')], default='lead', max_length=20)),
                ('total_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_pedidos', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre este cliente')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SuscriptorNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Suscriptores Newsletter',
                'ordering': ['-creado_en'],
            },
        ),
    ]
