# Generated by Django 4.2.30 on 2026-07-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_cliente_suscriptornewsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: HOCCE10, BLACKFRIDAY', max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentagem (%)'), ('fijo', 'Valor fixo (R$)')], default='porcentaje', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Si es porcentaje: 10 = 10%. Si es fijo: 15 = R$15,00', max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('usos_maximos', models.PositiveIntegerField(default=1, help_text='Cuántas veces se puede usar este cupón en total')),
                ('usos_actuales', models.PositiveIntegerField(default=0, editable=False)),
                ('compra_minima', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo de compra para poder usarlo (0 = sin mínimo)', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Cupones',
            },
        ),
    ]
